services:
  backend-app:
    container_name: backend-go
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - HOSTNAME=${HOSTNAME}
      - BACKEND_PORT=${BACKEND_PORT}

  frontend-app:
    container_name: frontend-next
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - PORT=${FRONTEND_PORT}

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - FRONTEND_PORT=${FRONTEND_PORT}
    depends_on:
      - backend-app
      - frontend-app
